---
# External routes generation
- name: Retrieving the cert to use when generating secrets for the {{ openshift_logging_elasticsearch_clustername }} cluster
  slurp:
    src: "{{ generated_certs_dir }}/{{ item.file }}"
  register: key_pairs
  with_items:
    - { name: "ca_file", file: "ca.crt" }
    - { name: "es_key", file: "system.logging.es.key" }
    - { name: "es_cert", file: "system.logging.es.crt" }

- name: Generating Elasticsearch route template for the cluster {{ openshift_logging_elasticsearch_clustername }}
  template:
    src: "{{ __base_file_dir }}/route_reencrypt.j2"
    dest: "{{mktemp.stdout}}/{{ openshift_logging_elasticsearch_clustername }}-route.yaml"
  vars:
    obj_name: "{{ openshift_logging_elasticsearch_clustername }}"
    route_host: "{{ openshift_logging_es_hostname }}"
    service_name: "{{ openshift_logging_elasticsearch_clustername }}"
    tls_dest_ca_cert: "{{ key_pairs | entry_from_named_pair('ca_file') | b64decode }}"
    edge_term_policy: "{{ openshift_logging_es_edge_term_policy | default('') }}"
    labels:
      component: support
      logging-infra: support
      provider: openshift
      cluster-name: "{{ openshift_logging_elasticsearch_clustername }}"
  changed_when: no

# This currently has an issue if the host name changes
- name: Setting Elasticsearch route for the cluster {{ openshift_logging_elasticsearch_clustername }}
  oc_obj:
    state: present
    name: "{{ openshift_logging_elasticsearch_clustername }}"
    namespace: "{{ openshift_logging_elasticsearch_namespace }}"
    kind: route
    files:
      - "{{ tempdir }}/{{ openshift_logging_elasticsearch_clustername }}-route.yaml"
    kubeconfig: '{{ kubeconfig }}'
