---
- set_fact:
    __es_num_of_shards: "{{ _es_configmap | default({}) | walk('index.number_of_shards', '1') }}"
    __es_num_of_replicas: "{{ _es_configmap | default({}) | walk('index.number_of_replicas', '0') }}"

# configmap
- template:
    src: jvm.options.j2
    dest: "{{ tempdir }}/jvm.options"
  when: es_jvm_options_contents is undefined
  changed_when: no

- template:
    src: log4j2.properties.j2
    dest: "{{ tempdir }}/log4j2.properties"
  when: es_log4j2_properties_contents is undefined
  changed_when: no

- template:
    src: elasticsearch.yml.j2
    dest: "{{ tempdir }}/elasticsearch.yml"
  vars:
    allow_cluster_reader: "{{ openshift_logging_elasticsearch_ops_allow_cluster_reader | lower | default('false') }}"
    es_number_of_shards: "{{ openshift_logging_es_number_of_shards | default(1) }}"
    es_number_of_replicas: "{{ openshift_logging_es_number_of_replicas | default(0) }}"
    es_kibana_index_mode: "{{ openshift_logging_elasticsearch_kibana_index_mode | default('unique') }}"
  when: es_config_contents is undefined
  changed_when: no

- copy:
    content: "{{ es_jvm_options_contents }}"
    dest: "{{ tempdir }}/jvm.options"
  when: es_jvm_options_contents is defined
  changed_when: no

- copy:
    content: "{{ es_log4j2_properties_contents }}"
    dest: "{{ tempdir }}/log4j2.properties"
  when: es_log4j2_properties_contents is defined
  changed_when: no

- copy:
    content: "{{ es_config_contents }}"
    dest: "{{ tempdir }}/elasticsearch.yml"
  when: es_config_contents is defined
  changed_when: no

- name: Set ES configmap
  oc_configmap:
    state: present
    name: "{{ node_configmap }}"
    namespace: "{{ openshift_logging_elasticsearch_namespace }}"
    from_file:
      elasticsearch.yml: "{{ tempdir }}/elasticsearch.yml"
      jvm.options: "{{ tempdir }}/jvm.options"
      log4j2.properties: "{{ tempdir  }}/log4j2.properties"

