---
__allowed_es_types: ["clientdatamaster", "data-master", "clientdata", "master", "client"]
__es_log_appenders: ['file', 'console']
__kibana_index_modes: ["unique", "shared_ops"]

__es_local_curl: "curl -s --cacert /etc/elasticsearch/secret/admin-ca --cert /etc/elasticsearch/secret/admin-cert --key /etc/elasticsearch/secret/admin-key"

__elasticsearch_ready_retries: "{{ openshift_logging_elasticsearch_poll_timeout_minutes | default(20) | int * 2 }}"

# TODO: integrate these
es_node_quorum: "{{ openshift_logging_elasticsearch_replica_count | int/2 + 1 }}"
es_min_masters_default: "{{ (openshift_logging_elasticsearch_replica_count | int / 2 | round(0,'floor') + 1) | int }}"
es_min_masters: "{{ (openshift_logging_elasticsearch_replica_count == 1) | ternary(1, es_min_masters_default) }}"
es_recover_after_nodes: "{{ openshift_logging_elasticsearch_replica_count | int }}"
es_recover_expected_nodes: "{{ openshift_logging_elasticsearch_replica_count | int }}"
full_restart_cluster: False
openshift_elasticsearch_recover_after_time: 5m

#es_masters_quorum: "{{ es_node_topology.masters.replicas |int /2 + 1 }}"
#es_recover_expected_data_nodes: "{{ es_node_topology.clientdata|length }}"
