---
__latest_es_version: "3_6"
__allowed_es_versions: ["3_5", "3_6", "3_7"]
__allowed_es_types: ["master", "clientdata", "clientdatamaster", "client", "data"]
__elasticsearch_log_appenders: ['file', 'console']
__kibana_index_modes: ["unique", "shared_ops"]

# TODO: integrate these
openshift_master_config_dir: "{{ openshift.common.config_base }}/master"
openshift_elasticsearch_recover_after_time: 5m

#es_masters_quorum: "{{ es_node_topology.masters.replicas |int /2 + 1 }}"
#es_recover_expected_data_nodes: "{{ es_node_topology.clientdata|length }}"
