---

- name: Create local temp directory for doing work in
  local_action: command mktemp -d /tmp/openshift-logging-certs-XXXXXX
  register: local_tmp
  changed_when: False
  check_mode: no
  become: no


- include: generate_certs.yaml
  vars:
 #    generated_certs_dir: "{{openshift.common.config_base}}/logging"
    pem_node_name: "{{ pem_node_name }}"


- name: Cleaning up local temp dir
  local_action: file path="{{local_tmp.stdout}}" state=absent
  tags: logging_cleanup
  changed_when: False
