---
- hosts: masters[0]
  roles:
  - role: openshift_logging_elasticsearch
    openshift_hosted_logging_cleanup: no
    openshift_elasticsearch_image: "t0ffel/elasticsearch-sg"
    openshift_elasticsearch_namespace: elasticsearch
    openshift_elasticsearch_init_image: "t0ffel/elasticsearch-init"
    kubeconfig: /home/anton/.kube/config
    certs_dir: /home/anton/src/openshift-ansible/certs/
    openshift_elasticsearch_secure: true

    es_node_topology:
      masters:
        replicas: 1
        limits:
          cpu: 200m
        requests:
          memory: 512Mi
      clients:
        replicas: 1
        limits:
          memory: 1024Mi
          cpu: 200m
      data:
      -
        node_storage_type: emptydir
        hostmount_path:
        - /mnt/data1
        - /mnt/data2
        limits:
          memory: 512Mi
          cpu: 200m
