---
# Install default storage classes in GCE & AWS
- name: Ensure storageclass object
  oc_storageclass:
    name: "{{ openshift_storageclass_name }}"
    default_storage_class: "{{ openshift_storageclass_default | default('true') | string}}"
    parameters: "{{ openshift_storageclass_parameters }}"
  run_once: true
