---
### Common settings
openshift_elasticsearch_image_prefix: "{{ openshift_hosted_deployer_prefix | default('docker.io/openshift/origin-') }}"
openshift_elasticsearch_image_version: "{{ openshift_hosted_deployer_version | default('latest') }}"
openshift_elasticsearch_image_pull_secret: "{{ openshift_hosted_image_pull_secret | default('') }}"
openshift_elasticsearch_namespace: logging
openshift_elasticsearch_sa_name: elasticsearch-sa

openshift_master_url: "https://kubernetes.default.svc.{{ openshift.common.dns_domain }}"

### Elasticsearch cluster topology
openshift_es_port: 9200
openshift_es_ca: /etc/fluent/keys/ca
openshift_es_client_cert: /etc/fluent/keys/cert
openshift_es_client_key: /etc/fluent/keys/key
openshift_elasticsearch_secure: false
openshift_elasticsearch_clustername: "elastic1"
openshift_elasticsearch_cluster_size: 1
## TODO: replace with computable cluster size
openshift_elasticsearch_recover_after_time: 5m

es_node_topology:
  masters:
    replicas: 2
    limits:
      #      memory: 1024Mi
      cpu: 200m
    nodeSelector:
      elasticsearch: "true"
      #label_name: label_value
    requests:
      memory: 512Mi
  clients:
    replicas: 1
    limits:
      memory: 1024Mi
      cpu: 200m
      #    nodeSelector:
      #label_name: label_value
  data:
  -
    nodeSelector:
      kubernetes.io/hostname: asherkho-ocp-rhel1.os1.phx2.redhat.com
    node_storage_type: hostmount
    hostmount_path:
    - /mnt/data1
    - /mnt/data2
    limits:
      memory: 2048Mi
      cpu: 200m
  -
    #nodeSelector:
    #  label_name: label_value
    node_storage_type: emptydir
    hostmount_path:
    - /mnt/data
    # ^^^ this needs to be a list for elasticsearch consumption.
    limits:
      memory: 2048Mi
      cpu: 200m

### Elasticsearch storage layout

# required if the PVC does not already exist
openshift_elasticsearch_pvc_size: ""
openshift_elasticsearch_pvc_dynamic: false
openshift_elasticsearch_pvc_pv_selector: {}
openshift_elasticsearch_pvc_access_modes: ['ReadWriteOnce']
openshift_elasticsearch_storage_group: '65534'

openshift_es_pvc_prefix: "{{ openshift_hosted_elasticsearch_pvc_prefix | default('logging-es') }}"

# this is used to determine if this is an operations deployment or a non-ops deployment
# simply used for naming purposes
openshift_elasticsearch_ops_deployment: false

openshift_logging_elasticsearch_ops_allow_cluster_reader: false

# following can be uncommented to provide values for configmaps -- take care when providing file contents as it may cause your cluster to not operate correctly
#es_contents:
#es_config_contents:


openshift_logging_es_ops_cluster_size: "{{ openshift_hosted_logging_elasticsearch_ops_cluster_size | default(1) }}"
openshift_elasticsearch_integration: false
