---
### Common settings
openshift_elasticsearch_image_prefix: "{{ openshift_hosted_deployer_prefix | default('docker.io/openshift/origin-') }}"
openshift_elasticsearch_image_version: "{{ openshift_hosted_deployer_version | default('latest') }}"
openshift_elasticsearch_image_pull_secret: "{{ openshift_hosted_image_pull_secret | default('') }}"
openshift_elasticsearch_namespace: logging
openshift_elasticsearch_sa_name: elasticsearch-sa

openshift_master_url: "https://kubernetes.default.svc.{{ openshift.common.dns_domain }}"

### Elasticsearch cluster topology
openshift_es_port: 9200
openshift_es_ca: /etc/fluent/keys/ca
openshift_es_client_cert: /etc/fluent/keys/cert
openshift_es_client_key: /etc/fluent/keys/key
openshift_elasticsearch_secure: false
openshift_elasticsearch_clustername: "elastic1"
openshift_elasticsearch_cluster_size: 1
openshift_elasticsearch_nodeselector: ""
openshift_elasticsearch_cpu_limit: 100m
openshift_elasticsearch_memory_limit: 2048Mi
openshift_elasticsearch_recover_after_time: 5m

es_node_topology:
  masters:
    replicas: 3
    limits:
      memory: 512Mi
      cpu: 100m
      #    nodeSelector:
      #label_name: label_value
  clients:
    replicas: 2
    limits:
      memory: 512Mi
      cpu: 100m
      #    nodeSelector:
      #label_name: label_value
  data:
  -
    #nodeSelector:
    #  label_name: label_value
    storage_type: emptydir
    hostmount_path: /mnt/data
    limits:
      memory: 512Mi
      cpu: 100m

  -
    #nodeSelector:
    #  label_name: label_value
    storage_type: emptydir
    hostmount_path: /mnt/data
    limits:
      memory: 512Mi
      cpu: 100m


# ES deployment type
openshift_elasticsearch_deployment_type: "data-master"

# ES deployment name
openshift_elasticsearch_deployment_name: ""

### Elasticsearch storage layout

# One of ['emptydir', 'pvc', 'hostmount']
openshift_elasticsearch_storage_type: "emptydir"

# hostmount options
openshift_elasticsearch_hostmount_path: ""

# pvc options
# the name of the PVC we will bind to -- create it if it does not exist
openshift_elasticsearch_pvc_name: ""

# required if the PVC does not already exist
openshift_elasticsearch_pvc_size: ""
openshift_elasticsearch_pvc_dynamic: false
openshift_elasticsearch_pvc_pv_selector: {}
openshift_elasticsearch_pvc_access_modes: ['ReadWriteOnce']
openshift_elasticsearch_storage_group: '65534'

openshift_es_pvc_prefix: "{{ openshift_hosted_elasticsearch_pvc_prefix | default('logging-es') }}"

# this is used to determine if this is an operations deployment or a non-ops deployment
# simply used for naming purposes
openshift_elasticsearch_ops_deployment: false

openshift_logging_elasticsearch_ops_allow_cluster_reader: false

# following can be uncommented to provide values for configmaps -- take care when providing file contents as it may cause your cluster to not operate correctly
#es_contents:
#es_config_contents:


openshift_logging_es_ops_cluster_size: "{{ openshift_hosted_logging_elasticsearch_ops_cluster_size | default(1) }}"
openshift_elasticsearch_integration: false
