---
# gen session_secret -- if necessary
# TODO: make idempotent
# - name: Generate proxy session
#   set_fact:
#     session_secret: "{{ 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' | random_word(200) }}"
#   check_mode: no

- name: Retrieving the cert to use when generating secrets for the logging components
  slurp:
    src: "{{ generated_certs_dir }}/{{ item.file }}"
  register: key_pairs
  with_items:
    - { name: "ca_file", file: "ca.crt" }
    - { name: "kibana_internal_key", file: "kibana-internal.key"}
    - { name: "kibana_internal_cert", file: "kibana-internal.crt"}

# gen oauth_secret -- if necessary
# TODO: make idempotent
- name: Generate oauth client secret
  set_fact:
    oauth_secret: "{{ 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' | random_word(64) }}"
  check_mode: no

# # create oauth client
# - name: Create oauth-client template
#   template:
#     src: oauth-client.j2
#     dest: "{{ tempdir }}/templates/oauth-client.yml"
#   vars:
#     kibana_hostname: "{{ openshift_logging_kibana_hostname }}"
#     secret: "{{ oauth_secret }}"
#
# - name: Set kibana-proxy oauth-client
#   oc_obj:
#     state: present
#     name: "kibana-proxy"
#     namespace: "{{ openshift_kibana_namespace }}"
#     kind: oauthclient
#     files:
#     - "{{ tempdir }}/templates/oauth-client.yml"
#     delete_after: true
#     kubeconfig: '{{ kubeconfig }}'

# create Kibana-proxy secret
- name: Set Kibana Oauth Proxy session secret
  oc_secret:
    state: present
    name: "kibana-session-secret"
    namespace: "{{ openshift_kibana_namespace }}"
#    files:
#    - name: server-key
#      path: "{{ generated_certs_dir }}/kibana-internal.key"
#    - name: server-cert
#      path: "{{ generated_certs_dir }}/kibana-internal.crt"
#    - name: server-tls
#      path: "{{ generated_certs_dir }}/server-tls.json"
    kubeconfig: '{{ kubeconfig }}'
    contents:
    # - path: oauth-secret
    #   data: "{{ oauth_secret }}"
    - path: session-secret
      data: "{{ session_secret }}"
    # - path: server-key
    #   data: "{{ key_pairs | entry_from_named_pair('kibana_internal_key') | b64decode }}"
    # - path: server-cert
    #   data: "{{ key_pairs | entry_from_named_pair('kibana_internal_cert') | b64decode }}"
    # - path: server-tls
    #   data: "{{ key_pairs | entry_from_named_pair('server_tls') | b64decode }}"

- name: Set Kibana Oauth Proxy tls secret
  oc_secret:
    state: present
    name: "kibana-oauth-tls"
    namespace: "{{ openshift_kibana_namespace }}"
    files:
    - name: tls.crt
      path: "{{ generated_certs_dir }}/kibana-internal.crt"
    - name: tls.key
      path: "{{ generated_certs_dir }}/kibana-internal.key"
    kubeconfig: '{{ kubeconfig }}'
