---
#- name: Gather OpenShift Logging Facts
#  openshift_logging_facts:
#    oc_bin: "{{openshift.common.client_binary}}"
#    admin_kubeconfig: "{{mktemp.stdout}}/admin.kubeconfig"
#    openshift_logging_namespace: "{{openshift_logging_namespace}}"
#  tags: logging_facts
#  check_mode: no

#- name: Validate Elasticsearch cluster size
#  fail: msg="The openshift_logging_es_cluster_size may only be scaled down manually. Please see official documentation on how to do this."
#  when: openshift_logging_facts.elasticsearch.deploymentconfigs | length > openshift_logging_es_cluster_size|int

#- name: Validate Elasticsearch Ops cluster size
#  fail: msg="The openshift_logging_es_ops_cluster_size may only be scaled down manually. Please see official documentation on how to do this."
#  when: openshift_logging_facts.elasticsearch_ops.deploymentconfigs | length > openshift_logging_es_ops_cluster_size|int

- name: Install logging
  include: "{{ role_path }}/tasks/install_support.yaml"
  when: openshift_hosted_logging_install | default(true) | bool


## Elasticsearch
# TODO: add more vars
- include_role:
    name: openshift_logging_elasticsearch
  vars:
    generated_certs_dir: "{{openshift.common.config_base}}/logging"
#    openshift_logging_es_pvc_name: "logging-es-1"

# TODO: add more vars
- include_role:
    name: openshift_logging_elasticsearch
  vars:
    generated_certs_dir: "{{openshift.common.config_base}}/logging"
    openshift_logging_es_ops_deployment: true
  when:
  - openshift_logging_use_ops | bool


## Kibana
- include_role:
    name: openshift_logging_kibana
  vars:
    generated_certs_dir: "{{openshift.common.config_base}}/logging"
#    openshift_logging_es_pvc_name: "logging-es-1"

# TODO: add more vars
- include_role:
    name: openshift_logging_kibana
  vars:
    generated_certs_dir: "{{openshift.common.config_base}}/logging"
    openshift_logging_kibana_ops_deployment: true
  when:
  - openshift_logging_use_ops | bool


## Fluentd
- include_role:
    name: openshift_logging_fluentd
  vars:
    generated_certs_dir: "{{openshift.common.config_base}}/logging"

- include: update_master_config.yaml
