---
- name: Create local temp directory for doing work in
  local_action: command mktemp -d /tmp/openshift-logging-ansible-XXXXXX
  register: local_tmp
  changed_when: False
  check_mode: no

- include: "{{ role_path }}/tasks/install_logging.yaml"
  when: openshift_logging_install_logging | default(false) | bool

- include: "{{ role_path }}/tasks/delete_logging.yaml"
  when:
    - not openshift_logging_install_logging | default(false) | bool

- name: Cleaning up local temp dir
  local_action: file path="{{local_tmp.stdout}}" state=absent
  tags: logging_cleanup
  changed_when: False
