---
- name: install elasticsearch
  hosts: masters
  roles:
  - role: openshift_logging_certs
    vars:
      generated_certs_dir: /home/centos/es-certs
      svc_name: elastic1
      kubeconfig: /home/centos/.kube/config
      openshift_logging_elasticsearch_allow_external: true
  - role: openshift_logging_elasticsearch
    vars:
      openshift_logging_image_version: latest
      openshift_logging_elasticsearch_namespace: "test-elasticsearch"
      openshift_logging_elasticsearch_clustername: "elastic1"
      openshift_logging_elasticsearch_sa_name: "sa-elasticsearch"
      openshift_logging_elasticsearch_clusterreader: false
      generated_certs_dir: /home/centos/es-certs
      openshift_logging_elasticsearch_transport_cert_name: "elasticsearch"
      openshift_logging_elasticsearch_api_cert_name: "logging-es"
      openshift_logging_elasticsearch_prometheus_sa: system:serviceaccount:elasticsearch:prometheus
      openshift_logging_elasticsearch_node_topology:
      - node_role:  master
        replicas: 3
        storage_group: 65534
        node_storage_type: emptydir
        limits:
          memory: 2Gi
        requests:
          memory: 1Gi
          cpu: 200m
        nodeSelector:
          elasticsearch: "true"
      - node_role:  clientdata
        storage_group: 65534
        node_storage_type: hostmount
        limits:
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 1Gi
        hostmount_path:
        - /mnt/disk2
        - /mnt/disk3
        nodeSelector:
          kubernetes.io/hostname: gprfc054.o.internal
      - node_role:  clientdata
        storage_group: 65534
        node_storage_type: hostmount
        limits:
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 1Gi
        hostmount_path:
        - /mnt/disk2
        - /mnt/disk3
        nodeSelector:
          kubernetes.io/hostname: gprfc056.o.internal
      - node_role:  clientdata
        storage_group: 65534
        node_storage_type: hostmount
        limits:
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 1Gi
        hostmount_path:
        - /mnt/disk2
        - /mnt/disk3
        nodeSelector: 
          kubernetes.io/hostname: gprfc059.o.internal
      openshift_logging_elasticsearch_log_appenders: console
      openshift_logging_elasticsearch_node_topology_defined: "true"
      openshift_logging_elasticsearch_allow_external: true
      openshift_logging_image_prefix: t0ffel/
      openshift_logging_elasticsearch_key: ''
      openshift_logging_elasticsearch_cert: ''
      openshift_logging_elasticsearch_ca_ext: ''
      openshift_logging_elasticsearch_hostname: es-test-elasticsearch.ose.sbu.lab.eng.bos.redhat.com
  - role: openshift_logging_kibana
    vars:
      generated_certs_dir: /home/centos/es-certs
      openshift_logging_kibana_namespace: "test-elasticsearch"
      openshift_logging_namespace: test-elasticsearch
#      openshift_logging_kibana_master_url: 
      openshift_logging_kibana_hostname: kibana-test-elasticsearch.ose.sbu.lab.eng.bos.redhat.com
#      openshift_logging_kibana_master_public_url: 
#      openshift_logging_kibana_replicas: "{{ openshift_logging_kibana_replica_count }}"
      openshift_logging_image_pull_secret: ''
      openshift_logging_kibana_es_host: "elastic1"
      openshift_logging_kibana_es_port: "9200"
      openshift_logging_image_prefix: t0ffel/
      kubeconfig: /home/centos/.kube/config
