- name: install elasticsearch
  hosts: masters
  roles:
  - role: openshift_logging_kibana
    vars:
      generated_certs_dir: /home/longuyen/prod-es-certs
      openshift_logging_kibana_namespace: "dh-stage-storage"
      openshift_logging_namespace: "dh-stage-storage"
      openshift_logging_kibana_master_url: https://kubernetes.default.svc.cluster.local
      openshift_logging_kibana_hostname: kibana.192.168.42.24.nip.io
      openshift_logging_kibana_master_public_url: kibana.192.168.42.24.nip.io
      openshift_logging_image_pull_secret: ''
      openshift_logging_kibana_es_host: "elastic1"
      openshift_logging_kibana_es_port: "9200"
      openshift_logging_image_version: latest
      openshift_logging_image_prefix: quay.io/longnguyennn/
      openshift_logging_kibana_proxy_image_prefix: "docker.io/openshift/"
      openshift_logging_kibana_proxy_image_version: "v1.0.0"
      kubeconfig: /home/longuyen/.kube/config
      __base_file_dir: 5.x
      openshift_image_tag: latest
