---
### General logging settings
openshift_logging_image_prefix: "{{ openshift_hosted_logging_deployer_prefix | default('docker.io/openshift/origin-') }}"
openshift_logging_image_version: "{{ openshift_hosted_logging_deployer_version | default('latest') }}"
openshift_logging_image_pull_secret: "{{ openshift_hosted_logging_image_pull_secret | default('') }}"
openshift_logging_master_url: "https://kubernetes.default.svc.{{ openshift.common.dns_domain }}"
openshift_logging_master_public_url: "{{ openshift_hosted_logging_master_public_url | default('https://' + openshift.common.public_hostname + ':' ~ (openshift_master_api_port | default('8443', true))) }}"
openshift_logging_namespace: logging

### Common settings
openshift_logging_curator_nodeselector: ""
openshift_logging_curator_cpu_limit: 100m
openshift_logging_curator_memory_limit: 512Mi

openshift_logging_curator_es_host: "logging-es"
openshift_logging_curator_es_port: 9200

# This should not exceed 1, should check for this
openshift_logging_curator_replicas: 1

# this is used to determine if this is an operations deployment or a non-ops deployment
# simply used for naming purposes
openshift_logging_curator_ops_deployment: false

# following can be uncommented to provide values for configmaps -- take care when providing file contents as it may cause your cluster to not operate correctly
#fluentd_config_contents:
#fluentd_throttle_contents:
#fluentd_secureforward_contents:
